# This is an intentionally broken deployment meant for me to experiment with PodMonitors
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vector
spec:
  interval: 24h
  url: https://helm.vector.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vector-aggregator-tls
  namespace: vector
  labels:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector-aggregator
    app.kubernetes.io/name: vector
spec:
  secretName: vector-aggregator-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - vector-aggregator.example.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
spec:
  interval: 30m
  chart:
    spec:
      chart: vector
      version: "0.42.x"
      sourceRef:
        kind: HelmRepository
        name: vector
      interval: 12h
  values:
    role: "Stateless-Aggregator"
    podMonitor:
      enabled: true
      additionalLabels:
        release: kube-prom-stack
    extraVolumes:
      - name: tls-certs
        secret:
          secretName: vector-aggregator-tls
    extraVolumeMounts:
      - name: tls-certs
        mountPath: /etc/vector/certs
        readOnly: true
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
        address: 127.0.0.1:8686
        playground: false
      sources:
        vector_metrics:
          type: internal_metrics
          scrape_interval_secs: 10
        vector_agents:
          address: 0.0.0.0:6000
          type: http_server
          encoding: json
          path: /
          method: POST
          tls:
            enabled: true
            crt_file: /etc/vector/certs/tls.crt
            key_file: /etc/vector/certs/tls.key
      transforms:
        vector_metrics_limit_cardinality:
          type: tag_cardinality_limit
          inputs:
            - vector_metrics
          mode: exact
        filter_vector_metrics:
          type: filter
          inputs:
            - vector_metrics
          condition: |
            match(.name, r'^vector_kafka_queue_messages') ||
            match(.name, r'^vector_kafka_produced_messages_total')
          # (match(.name, r'^vector_component_received_event_bytes_total') && .tags.component_id == "my_app_logs")
      sinks:
        prom-exporter:
          type: prometheus_exporter
          inputs:
            - vector_metrics_limit_cardinality
          address: 0.0.0.0:9598
        broken_kafka:
          type: kafka
          inputs:
            - vector_agents
          tls:
            enabled: true
          encoding:
            codec: raw_message
          bootstrap_servers: "wrong"
          topic: "wrong"
          sasl:
            enabled: true
            mechanism: SCRAM-SHA-512
            username: "fake"
            password: "fake"
      service:
        enabled: true
        type: "LoadBalancer"
        # annotations left out in local development
        ports:
          - name: vector-tls
            port: 443
            protocol: TCP
            targetPort: 6000
        shareProcessNamespace: true # Allows cert-reloader below to send signals to Vector
        extraContainers:
          - name: cert-reloader
            image: "busybox"
            command:
              - /bin/sh
              - -c
              - |
                apk add --no-cache inotify-tools procps
                echo "Certificate watcher started"
                while true; do
                  inotifywait -e modify,create,moved_to /etc/vector/certs/ 2>/dev/null
                  echo "Certificate change detected at $(date)"
                  sleep 2  # Brief pause to ensure file write is complete
                  VECTOR_PID=$(pgrep -f "vector" | head -1)
                  if [ -n "$VECTOR_PID" ]; then
                    echo "Sending SIGHUP to Vector (PID: $VECTOR_PID)"
                    kill -HUP $VECTOR_PID
                    echo "Reload signal sent, cooling down for 30s"
                    sleep 30
                  else
                    echo "Warning: Could not find Vector process"
                    sleep 5
                  fi
                done
            volumeMounts:
              - name: tls-certs
                mountPath: /etc/vector/certs
                readOnly: true
